spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed-api3
    username: root
    password: Death92g
  jpa:
    show-sql: true
    properties:
      hibernate:
        fotmat_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}